spring:
  datasource:
    url: ${JAWSDB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: shark-01.rmq.cloudamqp.com
    username: dxnatuly
    password: QLC3ih2z7r3d02ohgf0V47H1k3w03u60


rabbitmq:
  exchange:
    voting-result: voting-result-exchange
    DLX: result-dlx
  queue:
    voting-result: voting-result-queue
    DLX: result-dlx-queue
  routing-key:
    result: voting-result
    result-dlx: result-dlx
    result-dlx-queue: result-dlx-queue